name: Extract ZIP

on:
  workflow_dispatch:

permissions:
  contents: write
  workflows: write   # ← TAMBAHKAN INI

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract
        run: |
          find . -name "*.zip" -exec unzip -o {} \;
          rm -f *.zip
      - uses: stefanzweifel/git-auto-commit-action@v5
